version: "3.9"

services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 3s
      retries: 20

  web:
    build: .
    ports:
      - "8082:8000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DEBUG: "0"
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
      ALLOWED_HOSTS: ${ALLOWED_HOSTS}
      POSTGRES_HOST: db
      POSTGRES_PORT: "5432"
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      # Use host bind mounts if provided via env; fallback to named volumes for local dev
      - ${STATIC_MOUNT:-static}:/app/staticfiles
      - ${MEDIA_MOUNT:-media}:/app/media
    restart: always

  # nginx:
  #   image: nginx:1.27-alpine
  #   depends_on:
  #     - web
  #   ports:
  #     - "8080:80"
  #     - "8443:443"
  #   volumes:
  #     - ./docker/nginx.conf:/etc/nginx/nginx.conf:ro
  #     - ./docker/nginx.conf.template:/etc/nginx/templates/nginx.conf.template:ro
  #     - ./docker/nginx-entrypoint.sh:/docker-entrypoint.sh:ro
  #     - static:/static:ro
  #     - media:/media:ro
  #     - letsencrypt:/etc/letsencrypt
  #     - certbot-www:/var/www/certbot
  #   environment:
  #     - DOMAIN=${DOMAIN}
  #   entrypoint: ["/docker-entrypoint.sh"]
  #   restart: always

  # Автообновление контейнеров, если образы обновились в реестре
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --cleanup --interval 30
    restart: always

  certbot:
    image: certbot/certbot:latest
    volumes:
      - letsencrypt:/etc/letsencrypt
      - certbot-www:/var/www/certbot
    entrypoint: ["/bin/sh","-c"]
    # Renew certificates twice a day (initial issuance выполняется вручную командой ниже)
    command: "while :; do certbot renew --webroot -w /var/www/certbot --quiet; sleep 12h; done"
    restart: unless-stopped

volumes:
  pgdata:
  static:
  media:
  letsencrypt:
  certbot-www:
